FROM python:3

RUN useradd -ms /bin/bash amokryshev

WORKDIR /home/amokryshev

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY app ./

EXPOSE 8080/tcp

USER amokryshev

CMD [ "gunicorn", "server:app" ]